### PR TITLE
Build pysam, upstream glibc too new for us

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by nsoranzo** [comment]
What's the problem you're seeing with the PyPI wheels? In case we have similar issues with other packages.

**Comment by natefoo** [comment]
They are built for glibc 2.24, which is incompatible with EL7.

**Comment by nsoranzo** [comment]
Ah, right, you already mentioned that in https://github.com/galaxyproject/wheelforge/pull/9 , thanks @natefoo !
Should we open a PR upstream to request [these lines](https://github.com/pysam-developers/pysam/blob/master/.github/workflows/release.yaml#L63-L65) to be removed or changed to `manylinux2014` ?

**Comment by natefoo** [comment]
I guess, I assumed they had a reason for choosing `manylinux_2_24` over a wider/older standard like `manylinux2014`, but maybe thate isn't one.

**Pull request merged**
