### PR TITLE
Update pysam to 0.22.0

### PR DESCRIPTION
**Pull request by natefoo**

### CODE REVIEW

**Comment by natefoo** [comment]
`htslib/hts_probe_cc.sh` is in the repo but not the sdist, so the sdist can't be built with cibuildwheel even with the fix for `{project}`.

**Comment by natefoo** [comment]
Thanks! Sorry for the hacky fixes I used here.

**Comment by nsoranzo** [comment]
No problem!

**Comment by jmarshall** [comment]
Can you say more about the problem underlying the “fix for {project}” referred to?

**Comment by nsoranzo** [comment]
> Can you say more about the problem underlying the “fix for {project}” referred to?

@jmarshall I think we needed to expand the pysam tarball and cd into it in order to support https://github.com/pysam-developers/pysam/blob/master/pyproject.toml#L25-L27

**Pull request merged**
